#!/bin/bash

set -e

cd kokkos
cmake -Bbuild -DCMAKE_CXX_COMPILER=CC -DCMAKE_C_COMPILER=CC -DKokkos_ARCH_VEGA90A=ON -DCMAKE_CXX_EXTENSIONS=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON -DCMAKE_INSTALL_PREFIX=$RISTRA_INSTALL_PREFIX/kokkos -DKokkos_ENABLE_HIP=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DBUILD_SHARED_LIBS=ON
cd build
make -j${THREADS:-16} VERBOSE=1
make install
